run:
  deadline: 5m

linters:
  fast: false
  disable-all: true
  enable:
   # Enabled by Default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
   # Disabled by Default
    #- asasalint
    #- asciicheck
    #- bidichk
    #- bodyclose
    #- containedctx
    #- contextcheck
    #- cyclop
    #- decorder
    #- depguard
    #- dogsled
    #- dupl
    #- durationcheck
    #- errchkjson
    #- errname
    #- errorlint
    #- execinquery
    #- exhaustive
    #- exhaustivestruct !
    #- exhaustruct
    #- exportloopref
    #- forbidigo
    #- forcetypeassert
    #- funlen
    - gas
    #- gci
    #- gochecknoglobals
    #- gochecknoinits
    #- gocognit
    - goconst
    #- gocritic
    #- gocyclo
    #- godot
    #- godox
    #- goerr113
    - gofmt
    #- gofumpt
    #- goheader
    - goimports
    #- golint ! Use revive instead
    #- gomnd
    #- gomoddirectives
    #- gomodguard
    #- goprintffuncname
    #- gosec
    #- grouper
    #- ifshort !
    #- importas
    - interfacer # !
    #- ireturn
    #- lll
    #- maintidx
    #- makezero
    #- maligned # Replaced by govet 'fieldalignment'
    - megacheck
    #- misspell
    #- nakedret
    #- nestif
    #- nilerr
    #- nilnil
    #- nlreturn
    #- noctx
    #- nolintlint
    #- nonamedreturns
    #- nosnakecase !
    #- nosprintfhostport
    #- paralleltest
    #- prealloc
    #- predeclared
    #- promlinter
    - revive
    #- rowserrcheck
    #- scopelint !
    #- sqlclosecheck
    - structcheck
    #- stylecheck
    #- tagliatelle
    #- tenv
    #- testpackage
    #- thelper
    #- tparallel
    - unconvert
    #- unparam
    - usestdlibvars
    #- varnamelen
    #- wastedassign
    #- whitespace
    #- wrapcheck
    #- wsl
